# Generated by Django 4.1.7 on 2023-03-05 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculumEnvironment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectexam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectexam',
            name='exam_type',
            field=models.CharField(default='Test', max_length=20),
        ),
        migrations.CreateModel(
            name='SubjectExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
