# Generated by Django 4.1.7 on 2023-03-05 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumEnvironment', '0002_alter_subjectexam_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectexam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='SubjectExamResult',
        ),
    ]
